import React,{useEffect,useState} from 'react';
import {Database,RefreshCw,ShieldCheck,Search} from 'lucide-react';
import {nyxosApi} from '../../services/nyxosApi';
interface Props{onNotify:(type:'info'|'success'|'warning'|'alert',title:string,message:string)=>void}
export const ColetaDatasetModule:React.FC<Props>=({onNotify})=>{
 const [ctx,setCtx]=useState<any>(null); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true);
 const refresh=async()=>{setLoading(true);try{setCtx(await nyxosApi.getDatasetContext());}finally{setLoading(false);}}; useEffect(()=>{refresh();},[]);
 const exportJson=()=>{const blob=new Blob([JSON.stringify(ctx,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nyxos_dual_dataset_${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href);onNotify('success','Dataset exportado','Contexto real do coletor AE5 exportado.');};
 const q=ctx?.datasets?.qwen?.registros??0,k=ctx?.datasets?.kernel?.registros??0;
 return <div className="flex h-full flex-col bg-[#0b0c13] text-zinc-100 select-text"><div className="flex items-center justify-between border-b border-white/5 px-6 py-3.5 bg-black/20"><div className="flex items-center gap-3"><Database className="h-4 w-4 text-violet-400"/><div className="text-xs"><span className="font-medium text-zinc-200">Coleta Dual de Dataset AE5</span><span className="mx-2 text-zinc-600">·</span><span className="text-zinc-400 font-mono">Qwen + Kernel</span></div></div><button onClick={refresh} className="rounded border border-white/10 p-2 text-zinc-300 hover:bg-white/5"><RefreshCw className={`h-3.5 w-3.5 ${loading?'animate-spin':''}`}/></button></div>
 <div className="flex items-center justify-between px-6 py-2.5 border-b border-white/5"><div className="flex items-center gap-2 rounded bg-black/50 border border-white/10 px-2.5 py-1 text-xs w-64"><Search className="h-3.5 w-3.5 text-zinc-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar no contexto..." className="w-full bg-transparent text-white focus:outline-none"/></div><div className="flex items-center gap-3 text-xs font-mono text-zinc-400"><span>Qwen: {q}</span><span>Kernel: {k}</span>{ctx?.treinamento_automatico===false&&<span className="text-emerald-400 flex items-center gap-1"><ShieldCheck className="h-3.5 w-3.5"/> sem treino automático</span>}<button onClick={exportJson} className="text-violet-300 hover:text-white">Exportar</button></div></div>
 <div className="flex-1 overflow-y-auto p-6"><pre className="rounded border border-white/5 bg-black/30 p-4 text-[11px] leading-relaxed text-zinc-400 whitespace-pre-wrap">{JSON.stringify(ctx,null,2).split('\n').filter(l=>!search||l.toLowerCase().includes(search.toLowerCase())).join('\n')}</pre></div></div>;
};