import React,{useEffect,useRef,useState} from 'react';
import {Volume2,Mic,Sparkles,Play,Square} from 'lucide-react';
import {NyxalState} from '../../types/nyxos';
import {nyxosApi} from '../../services/nyxosApi';
interface Props{currentNyxalState:NyxalState;onSetState:(s:NyxalState)=>void;onNotify:(type:'info'|'success'|'warning'|'alert',title:string,message:string)=>void}
export const PresencaAudioModule:React.FC<Props>=({currentNyxalState,onSetState,onNotify})=>{
 const [phrase,setPhrase]=useState('Sistemas prontos. Estou pronta para operar o computador.');const[speaking,setSpeaking]=useState(false);const[listening,setListening]=useState(false);const media=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
 const speak=async()=>{if(speaking)return;setSpeaking(true);onSetState('EXECUTANDO');try{await nyxosApi.speak(phrase);onSetState('CONCLUIDO');}catch(e:any){onSetState('ERRO');onNotify('alert','TTS indisponível',e.message);}finally{setSpeaking(false);}};
 const start=async()=>{if(listening)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream);media.current=rec;chunks.current=[];rec.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setListening(false);onSetState('PROCESSANDO');try{const text=await nyxosApi.transcribe(new Blob(chunks.current,{type:rec.mimeType||'audio/webm'}));setPhrase(text||phrase);onSetState('CONCLUIDO');if(text)onNotify('success','STT concluído',text);}catch(e:any){onSetState('ERRO');onNotify('alert','STT indisponível',e.message);}};rec.start();setListening(true);onSetState('OUVINDO');}catch(e:any){onNotify('alert','Microfone indisponível',e.message);}};
 const stop=()=>{media.current?.stop();};
 return <div className="flex h-full flex-col bg-[#0b0c13] text-zinc-100 select-text"><div className="flex items-center justify-between border-b border-white/5 px-6 py-3.5 bg-black/20"><div className="flex items-center gap-3"><Sparkles className="h-4 w-4 text-violet-400"/><div className="text-xs"><span className="font-medium text-zinc-200">Presença & Síntese Vocal</span><span className="mx-2 text-zinc-600">·</span><span className="text-zinc-400 font-mono">Kokoro TTS + Whisper STT</span></div></div></div><div className="flex-1 overflow-y-auto p-6 space-y-5">
 <div className="rounded border border-white/5 bg-black/30 p-5"><div className="text-xs font-semibold uppercase tracking-wider text-zinc-400 font-mono mb-3">Estado da Presença Nyxal</div><div className="font-mono text-violet-300 text-sm">{currentNyxalState}</div></div>
 <div className="rounded border border-white/5 bg-black/30 p-5 space-y-4"><div className="flex items-center gap-2 text-xs font-semibold text-zinc-200 font-mono"><Volume2 className="h-4 w-4 text-violet-400"/>TTS real</div><textarea value={phrase} onChange={e=>setPhrase(e.target.value)} className="w-full rounded border border-white/10 bg-black/50 px-3 py-2 text-xs text-zinc-200 focus:outline-none min-h-20"/><button onClick={speak} disabled={speaking} className="flex items-center gap-2 rounded bg-violet-600 px-4 py-2 text-xs text-white disabled:opacity-50"><Play className="h-3.5 w-3.5"/>{speaking?'Sintetizando…':'Executar Voz Nyxal'}</button></div>
 <div className="rounded border border-white/5 bg-black/30 p-5 space-y-4"><div className="flex items-center gap-2 text-xs font-semibold text-zinc-200 font-mono"><Mic className="h-4 w-4 text-violet-400"/>STT real via API</div><div className="flex gap-2"><button onClick={listening?stop:start} className="flex items-center gap-2 rounded border border-white/10 px-4 py-2 text-xs text-zinc-200 hover:bg-white/5">{listening?<Square className="h-3.5 w-3.5"/>:<Mic className="h-3.5 w-3.5"/>}{listening?'Parar captura':'Iniciar captura'}</button></div><p className="text-[11px] text-zinc-500">O áudio é enviado ao /api/stt e transcrito pelo backend NyxOS.</p></div>
 </div></div>;
};