import React,{useEffect,useState} from 'react';
import {Layers,RefreshCw,ShieldCheck} from 'lucide-react';
import {nyxosApi} from '../../services/nyxosApi';
import {SystemService} from '../../types/nyxos';
interface Props{onNotify:(type:'info'|'success'|'warning'|'alert',title:string,message:string)=>void}
export const ResidenciaModule:React.FC<Props>=({onNotify})=>{
 const [services,setServices]=useState<SystemService[]>([]); const [loading,setLoading]=useState(true);
 const refresh=async()=>{setLoading(true);try{setServices(await nyxosApi.getSystemServices());}catch(e:any){onNotify('alert','Residência indisponível',e.message);}finally{setLoading(false);}}; useEffect(()=>{refresh();const id=setInterval(refresh,5000);return()=>clearInterval(id);},[]);
 return <div className="flex h-full flex-col bg-[#0b0c13] text-zinc-100 select-text"><div className="flex items-center justify-between border-b border-white/5 px-6 py-3.5 bg-black/20"><div className="flex items-center gap-3"><Layers className="h-4 w-4 text-violet-400"/><div className="text-xs"><span className="font-medium text-zinc-200">Residência Gerenciada</span><span className="mx-2 text-zinc-600">·</span><span className="text-zinc-400 font-mono">systemd · somente leitura</span></div></div><button onClick={refresh} className="rounded border border-white/10 p-2"><RefreshCw className={`h-3.5 w-3.5 ${loading?'animate-spin':''}`}/></button></div>
 <div className="flex-1 overflow-y-auto p-6 space-y-3"><div className="rounded border border-emerald-500/20 bg-emerald-950/10 p-4 text-xs text-zinc-300"><div className="flex items-center gap-2 font-mono text-emerald-400"><ShieldCheck className="h-4 w-4"/>OBSERVAÇÃO REAL DO SYSTEMD</div><p className="mt-2">O Display lê o estado das unidades residentes publicadas pela API do NyxOS. Reinicialização permanece sob o supervisor residente.</p></div>{services.map(s=><div key={s.name} className="rounded border border-white/5 bg-black/40 p-4"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><span className="font-mono text-xs font-semibold text-white">{s.name}</span><span className={`text-[10px] font-mono px-2 py-0.5 rounded ${s.status==='active'?'bg-emerald-500/10 text-emerald-400':'bg-red-500/10 text-red-400'}`}>{s.subState.toUpperCase()}</span></div><p className="mt-1 text-xs text-zinc-400">{s.description}</p></div><div className="text-right text-[11px] font-mono text-zinc-400">{s.pid&&<div>PID {s.pid}</div>}<div>{s.memoryUsageMb} MB</div></div></div></div>)}</div></div>;
};