import React,{useState,useEffect,useRef} from 'react';
import {Mic,ArrowRight,X,Volume2,Square} from 'lucide-react';
import {nyxosApi} from '../../services/nyxosApi';
import {NyxalState,NyxalMessage,ModuleWindowId} from '../../types/nyxos';
interface Props{isOpen:boolean;onClose:()=>void;onOpenModule:(id:ModuleWindowId)=>void;onStateChange:(s:NyxalState)=>void;onNotify:(type:'info'|'success'|'warning'|'alert',title:string,message:string)=>void}
export const NyxalQuickSummon:React.FC<Props>=({isOpen,onClose,onOpenModule,onStateChange,onNotify})=>{
 const[input,setInput]=useState('');const[messages,setMessages]=useState<NyxalMessage[]>([{id:'welcome',sender:'nyxal',text:'O que você precisa?',timestamp:'Agora'}]);const[listening,setListening]=useState(false);const[busy,setBusy]=useState(false);const inputRef=useRef<HTMLInputElement>(null);const endRef=useRef<HTMLDivElement>(null);const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
 useEffect(()=>{if(isOpen)setTimeout(()=>inputRef.current?.focus(),50)},[isOpen]);useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[messages]);
 if(!isOpen)return null;
 const submit=async(e?:React.FormEvent)=>{e?.preventDefault();const query=input.trim();if(!query||busy)return;setInput('');setMessages(m=>[...m,{id:`u-${Date.now()}`,sender:'user',text:query,timestamp:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}]);setBusy(true);try{const reply=await nyxosApi.converseWithNyxal(query,onStateChange);setMessages(m=>[...m,reply]);await nyxosApi.speak(reply.text);}catch(err:any){onStateChange('ERRO');onNotify('alert','Nyxal indisponível',err.message);}finally{setBusy(false);onStateChange('ONLINE');}};
 const startVoice=async()=>{if(listening)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream);recorder.current=rec;chunks.current=[];rec.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setListening(false);onStateChange('PROCESSANDO');try{const text=await nyxosApi.transcribe(new Blob(chunks.current,{type:rec.mimeType||'audio/webm'}));setInput(text);onStateChange('ONLINE');}catch(e:any){onStateChange('ERRO');onNotify('alert','STT indisponível',e.message)}};rec.start();setListening(true);onStateChange('OUVINDO')}catch(e:any){onNotify('alert','Microfone indisponível',e.message)}};
 const stopVoice=()=>recorder.current?.stop();
 const handleAction=(target:string)=>{if(['vps','delta','residencia','gateway','presenca','dataset','terminal','arquivos'].includes(target)){onOpenModule(target as ModuleWindowId);onClose();}};
 return <div className="nyxal-command-overlay fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-md p-4" onClick={onClose}><div className="nyxal-command-panel w-full max-w-xl rounded-xl border border-white/10 bg-[#0d0e16]/95 shadow-2xl overflow-hidden" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b border-white/5 px-5 py-3.5 bg-black/30"><span className="font-mono text-xs font-semibold tracking-wider text-zinc-300">NYXAL CONVERSA · API REAL</span><button onClick={onClose}><X className="h-4 w-4"/></button></div><div className="max-h-80 min-h-48 overflow-y-auto p-5 space-y-3.5 select-text">{messages.map(m=><div key={m.id} className={`flex flex-col ${m.sender==='nyxal'?'items-start':'items-end'}`}><div className={`max-w-[85%] rounded-lg px-4 py-2.5 text-xs leading-relaxed ${m.sender==='nyxal'?'bg-black/40 border border-white/5 text-zinc-200':'bg-violet-600/90 text-white'}`}>{m.text}{m.suggestedAction&&<button onClick={()=>handleAction(m.suggestedAction!.target)} className="mt-2 block text-[11px] text-violet-300"><ArrowRight className="inline h-3 w-3"/>{m.suggestedAction.label}</button>}</div><span className="mt-1 text-[10px] font-mono text-zinc-600">{m.timestamp}</span></div>)}<div ref={endRef}/></div><form onSubmit={submit} className="flex items-center gap-2 border-t border-white/5 p-4"><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} disabled={busy} placeholder="Fale com a Nyxal..." className="flex-1 bg-transparent text-xs text-white focus:outline-none"/><button type="button" onClick={listening?stopVoice:startVoice} className="rounded border border-white/10 p-2 text-zinc-300">{listening?<Square className="h-4 w-4"/>:<Mic className="h-4 w-4"/>}</button><button disabled={busy} className="rounded border border-white/10 p-2 text-zinc-300"><Volume2 className="h-4 w-4"/></button></form></div></div>;
};